// <auto-generated />
using System;
using Avaliacoes.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avaliacoes.Migrations
{
    [DbContext(typeof(AvaDbContext))]
    [Migration("20250608232601_LastMigration2")]
    partial class LastMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Avaliacoes.Models.Opiniao", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Produtoid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("comentarios")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("id_produto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("nota")
                        .HasColumnType("double");

                    b.Property<string>("opiniao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Produtoid");

                    b.ToTable("Opinioes");
                });

            modelBuilder.Entity("Avaliacoes.Models.Produto", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("preco")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Avaliacoes.Models.Opiniao", b =>
                {
                    b.HasOne("Avaliacoes.Models.Produto", null)
                        .WithMany("opinioes")
                        .HasForeignKey("Produtoid");
                });

            modelBuilder.Entity("Avaliacoes.Models.Produto", b =>
                {
                    b.Navigation("opinioes");
                });
#pragma warning restore 612, 618
        }
    }
}
